### ISSUE TITLE
pycryptodomex vs pycryptodome - ModuleNotFound error

### ISSUE THREAD

**Issue by robot-army** [JsBergbau/MiTemperature2#100]
Hi, 

Using the instructions in the README for scanning ATC firmware devices requires installation of the Cryptodome library. 

When using the command in the readme `pip install pycryptodome`, running the script fails with `ModuleNotFoundError: No module named 'Cryptodome'`

using `pip3 install pycryptodomex` works. I suggest also that `pip3` rather than `pip` should be used for consistency with other commands. 

Is this expected/correct? I found the suggestion here: https://github.com/DP-3T/reference_implementation/issues/1

Thanks.

**Comment by JsBergbau** [comment]
Hi robot-army,

thanks for your message. You're absolutely right. I've corrected to `pip3` and `pycryptodomex`. That happens when multiple requirements were installed on development system.
