### ISSUE TITLE
Question: Multiple sensors/influxdb?

### ISSUE THREAD

**Issue by hancockks** [JsBergbau/MiTemperature2#117]
Looking at sendToInflux.sh, I'm not sure whether we can combine this with the sensors.ini file to send multiple sensors to influx at the same time or whether one has to run the process in parallel, once for each sensor?

**Comment by JsBergbau** [comment]
Hallo hancockks,

Multiple sensor is no problem, since the sensorname comes from sensors.ini and works as tag for the sensors. Just have a look at the callback file https://github.com/JsBergbau/MiTemperature2/blob/master/sendToInflux.sh

**Comment by JsBergbau** [comment]
>  The callback will call sendToInflux.sh once for each sensor?

Exactly. 

Using skip identical option is indepent of the callback.
