### ISSUE TITLE
Script issue

### ISSUE THREAD

**Issue by maresob** [JsBergbau/MiTemperature2#12]
Hi, 
I have a problem can anyone help??

  File "./LYWSD03MMC.py", line 20
    temperature: float
               ^
SyntaxError: invalid syntax

**Comment by JsBergbau** [comment]
Please execute 
`python3 --version`
Looks like you're not using Python 3.7 as required.

**Comment by CurikovMF** [comment]
приветствую 
у меня та же проблема 

 File "./LYWSD03MMC.py", line 20
    temperature: float
               ^
SyntaxError: invalid syntax
pi@homebridge:~/MiTemperature2 $ python --version
Python 2.7.13
pi@homebridge:~/MiTemperature2 $ python3.7 --version
Python 3.7.0
pi@homebridge:~/MiTemperature2 $ python3 --version
Python 3.7.0

**Comment by JsBergbau** [comment]
Please go to directory where LYWSD03MMC.py and try `python3 LYWSD03MMC.py`

**Comment by JsBergbau** [comment]
Seems to be solved --> Closing
