### ISSUE TITLE
List of dependencies not complete

### ISSUE THREAD

**Issue by skibbipl** [JsBergbau/MiTemperature2#122]
So I tried to install the script on freshly installed raspbian os upgraded to testing/bookworm and when I tried to install bluepy, `pip` complained about missing `glib.h`. So I had to install `libglib2.0-dev` package. Perhaps it's worth adding it to dependencies?
Also currently there is an issue with `pybluez` so to install it correctly I used following command:
```
pip3 install git+https://github.com/pybluez/pybluez.git#egg=pybluez
```

**Comment by SHAdaVinci** [comment]
Hi,
I can confirm on Debian testing/Bookworm (as of 2023-04-12)

I couldn't install bluepy until installed `libglib2.0-dev` as per [Installation](https://github.com/IanHarvey/bluepy#installation) section of [bluepy repository](https://github.com/IanHarvey/bluepy)

```sh
sudo apt-get install python3-pip libglib2.0-dev
pip3 install bluepy
```

OS: Debian 12 Bookworm
Python: 3.11.2
Pip: 23.0.1
