### ISSUE TITLE
ModuleNotFoundError: No module named 'cryptoFunctions'

### ISSUE THREAD

**Issue by wojciewa** [JsBergbau/MiTemperature2#143]
Hi,
Probably the problem is trivial, but unfortunately, I can't find a solution. When I try to run the script in passive mode, an error message appears about a missing module. In which package is this module located?

![screen](https://github.com/JsBergbau/MiTemperature2/assets/9107657/970d016a-7df0-4069-8888-371f33fd65b0)

Regards
Wojtek

**Comment by JsBergbau** [comment]
Hi wojciewa,

it looks like you've downloaded only LYWSD03MMC.py. In this repo, there is also the required `cryptoFunctions.py`

**Comment by wojciewa** [comment]
Hi,
this was so simple/obvious. I'm embarrassed...
Thanks
Wojtek
