### ISSUE TITLE
In Hassio (HassOS) cant install bluepy

### ISSUE THREAD

**Issue by antoweb** [JsBergbau/MiTemperature2#16]
Hi, the python script wont work in my hassio because missing bluepy:

~ $ ./LYWSD03MMC.py -d A4:C1:38:XX:XX:XX -r -b 5
Traceback (most recent call last):
File "./LYWSD03MMC.py", line 5, in
from bluepy import btle
ModuleNotFoundError: No module named 'bluepy'

and installing pip3 install bluepy canot find make

**Comment by JsBergbau** [comment]
Please try in hassio forum how to install bluepy.
