### ISSUE TITLE
[Feature Request] Adapter selection option

### ISSUE THREAD

**Issue by wiewiur** [JsBergbau/MiTemperature2#22]
I think possibility of selecting bluetooth adapter if we have more than one (hci0 hci1 etc.) would be very useful.

**Comment by JsBergbau** [comment]
Hi,

could you describe your usecase for multiple interfaces a bit more? I'm just curious.

I've implemented interface selection, use -i or --interface 1 for hci1 and so on.

Please give me short feedback if it works the way you wanted.

**Comment by wiewiur** [comment]
I have raspbery PI and I wanted to use external BT dongle beacuse of range issues with internal BT module. Im testing and it looks OK for now.
Thanks

**Comment by JsBergbau** [comment]
What PI do you have? In the last days there was a firmware issue with reduced bluetooth range. It should be fixed now. If you still have problems with range you can try `sudo apt-get install bluez=5.50-1+rpt1`

**Comment by wiewiur** [comment]
RPI4 in metal case :)

**Comment by JsBergbau** [comment]
The Armorcase https://www.berrybase.de/neu/armor-geh-228-use-f-252-r-raspberry-pi-4-schwarz or another? With that the antenna stays free, it just gets a bit more directional :)

**Comment by wiewiur** [comment]
No, its full case: https://www.aliexpress.com/item/4000494307148.html

**Comment by JsBergbau** [comment]
Ok, you really should use an external adapter :)
