### ISSUE TITLE
SyntaxWarning: "is not" with a literal

### ISSUE THREAD

**Issue by michaelnimbs** [JsBergbau/MiTemperature2#24]
`LYWSD03MMC.py:313: SyntaxWarning: "is not" with a literal. Did you mean "!="?`
`if bluepypid is not 0:`

https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal

**Comment by JsBergbau** [comment]
This is a new behaviour of Python 3.8. SInce it works I'll fix it with the next update on the script.

**Comment by JsBergbau** [comment]
Fixes in v1.7 release
