### ISSUE TITLE
Insert data on a Magic Mirror

### ISSUE THREAD

**Issue by rubenix** [JsBergbau/MiTemperature2#31]
Hello got this working on a pi3B. 
Reads values from sensor and sores them on a txt file but don't know how to show this data.txt on my Magic Mirror. Any ideas? Sorry but Im not a coder...

**Comment by JsBergbau** [comment]
Sorry, I can't tell you either. You should ask your question at the magic mirror project.

**Comment by rubenix** [comment]
Thanks for your answer; did that already. hope someone can gimme a hand with this.
Thanks for such a nice work here!
