### ISSUE TITLE
Option to connect, get data, than go to sleep for defined time

### ISSUE THREAD

**Issue by Ri100** [JsBergbau/MiTemperature2#38]
Hallo JS Bergbauer,

what do you think about adding an option to connect to to the sensor based on defined time intervals (e.g. 1h), get the data, and put it to sleep for the defined time period (1h). This should extend battery life in cases when measurements don't need to be very frequent.

Gruß
Christo

**Comment by JsBergbau** [comment]
Hi, this mode is already implemented. Just use the --count option. After that script exits. You can trigger it every hour via cron or put in a script where it sleeps 60 min, just as you like.

**Comment by Ri100** [comment]
Alright, thanks.
Sorry for the unnecessary issue than.
