### ISSUE TITLE
syntaxError

### ISSUE THREAD

**Issue by effendieffendi** [JsBergbau/MiTemperature2#43]
Hi,

I can't get a virtual sensor on Supla
With a command:

./LYWSD03MMC.py -d A4:C1:38:AA:6E:C6 -r -b

I get the response:

  File "./LYWSD03MMC.py", line 20
    temperature: float
               ^
SyntaxError: invalid syntax

Any help?

**Comment by JsBergbau** [comment]
Please execute `python --version`
Your version must be at least 3,7 or above.
