### ISSUE TITLE
Use usb bluetooth dongle instead of builtin bluetooth

### ISSUE THREAD

**Issue by acca84** [JsBergbau/MiTemperature2#48]
Hello
I'm using your library on a raspberry pi 4.
i was using it with an odroid c2 and usb bluetooth adapter, the range was better.

is that possible to use this bluetooth dongle instead of the builtin bluetooth of pi 4 ?
thanks

**Comment by JsBergbau** [comment]
Yes, this is possible, see Readme.md https://github.com/JsBergbau/MiTemperature2/blob/master/README.md#usage
--interface N, -i N   Specifiy the interface number to use, e.g. 1 for hci1

**Comment by acca84** [comment]
Ok, thank you very much for your work !
