### ISSUE TITLE
How to use with home-assistant?

### ISSUE THREAD

**Issue by Luilutin** [JsBergbau/MiTemperature2#6]
Hi! 

How I can use this script with home-assistant? I know at this use more battery use way, but I want use my sensor

**Comment by JsBergbau** [comment]
I don't use home-assistant, so I can't help you, sorry. You should ask at home assistant community how to integrate external data.
BTW: After 2 weaks constantly polling, still 99 % battery.

**Comment by AnthonyKNorman** [comment]
See my repository here https://github.com/AnthonyKNorman/Xiaomi_BLE_Tempertaure_Display_for_HA
I am using this code with minor tweaks.
