### ISSUE TITLE
Incorrect helptext for devicelistfile in ATC mode

### ISSUE THREAD

**Issue by dotdavid** [JsBergbau/MiTemperature2#66]
Hi, great job with this script. It has been good to play around with these sensors using it.

I noticed when running in ATC mode the following message is displayed.

>Script started in ATC Mode
>----------------------------
>In this mode all devices within reach are read out, unless a namefile and --namefileonlydevices is specified.
>Also --name Argument is ignored, if you require names, please use --namefile .

I assume "namefile" should read "devicelistfile" and "namefileonlydevices" should read "onlydevicelist".

I would raise a simple PR but to be honest I'm not too familiar with Git and Github, and I figured it would be too minor a fix to bother with :-)

**Comment by JsBergbau** [comment]
Hi dotdavid,

thanks for noticing and reporting this. Yeah you're right. It was intended as you describe.

I've just uploaded the fix.
