### ISSUE TITLE
Run on windows 10

### ISSUE THREAD

**Issue by amitmargalit** [JsBergbau/MiTemperature2#70]
I got an LYWSD03MMC in a room with an always running win10. Is it possible to run anything similar to get the advertised data?
My Mac running HomeBridge is too far away.

**Comment by JsBergbau** [comment]
Hi amitmargalit,

thanks for your request. The used librarys only support Linux, so porting this to windows would mean a lot of work. Most users use small linux devices like Rasperry Pi to collect measurements, so the number of users would be quite small.

You could run a small linux machine via virtualBox inside windows or maybe even Hyper-V and pass through a USB bluetooth dongle to linux. That would work.
