### ISSUE TITLE
RSSI not being read

### ISSUE THREAD

**Issue by g0lgs** [JsBergbau/MiTemperature2#73]
I am not getting RSSI values reported by the script (if I use a callback I can see it is always sending a 0 values)

```
python3 ./LYWSD03MMC.py -d A4:C1:38:BD:FC:24 --battery --round --debounce --rssi 
Trying to connect to A4:C1:38:BD:FC:24
Temperature: 25.5
Humidity: 39
Battery voltage: 3.022 V
Battery level: 92

Temperature: 25.5
Humidity: 39
Battery voltage: 3.022 V
Battery level: 92

```

**Comment by JsBergbau** [comment]
Hi g9lgs,

RSSI is only available in ATC Mode, thats why this command is in the section "ATC related arguments". 
I found no way to get RSSI in connected mode. According to https://stackoverflow.com/a/24417605/11890443 for Bluetooth LE devices the only way to get RSSI is while scanning. ATC mode scans all the time, thats why we get RSSI there.

**Comment by g0lgs** [comment]
Thanks for the Clarification - I had noticed that --devicelistfile required ATC mode but missed that --rssi requiredfthat too.
