### ISSUE TITLE
When will the procedure for parsing Advertising packages be corrected in accordance with the Bluetooth LE standard?

### ISSUE THREAD

**Issue by pvvx** [JsBergbau/MiTemperature2#79]
When will the procedure for parsing Advertising packages be corrected in accordance with the Bluetooth LE standard?
An advertisement package has the right to contain several AD-sections. This is standard in BLE.
![image](https://user-images.githubusercontent.com/12629515/114117136-b3233700-98ee-11eb-8a7a-d7275a431bc7.png)

https://github.com/JsBergbau/MiTemperature2/blob/master/LYWSD03MMC.py#L445-L450 ?

'atcIdentifier' is a UUID and preceded by an identifier that it is a 16 bit UUID. 
The AD structure also has its own size.
...

**Comment by JsBergbau** [comment]
It worked perfectly for original ATC1441 firmware advertisments :)
Then a new advertisment format came up which was only distinguishable from orginal ATC1441 format by its length. If not filtering this paket wrong measurements were decoded. Sometimes we code things and even have no clue that this code might break compatibility with other solutions.

However I'll do my best to improve it. Can you give me a hint how to easily change it to support v2.9 without breaking compatibility?

**Comment by pvvx** [comment]
https://github.com/pvvx/ATC_MiThermometer/issues/79#issuecomment-808807418

This flags parameter gives the device visibility in standard applications for Windows, Android, ...
In the current firmware version 3.0, the addition of "Ad-flags" is switched in the settings and depends on the user's choice.

**Comment by pvvx** [comment]
> Then a new advertisment format came up which was only distinguishable from orginal ATC1441 format by its length. 

This is enough to determine that the data structure is different.

> However I'll do my best to improve it. Can you give me a hint how to easily change it to support v2.9 without breaking compatibility?

Parse the ad package in the same way as all other software does.

Length PDU, AD length, AD Type, AD data, [ end Length PDU? ]  ADn length, ADn Type, ADn-data...

Known  AD-Type? id = 16-bit UUID? -> Known UUID? -> we process by AD-Length AD-data, ...

**Comment by JsBergbau** [comment]
Support for Firmware v2.9 is now added. Thank you very much for also supporting the shorter "old" packet format with 32 Bytes length which is active when checkbox is not checked:
![grafik](https://user-images.githubusercontent.com/37013344/114183406-f4920180-9943-11eb-8bc9-c2ee87fb33be.png)

When checkbox is checked packet length is 35 bytes and is also now decoded correctly
![grafik](https://user-images.githubusercontent.com/37013344/114183475-04a9e100-9944-11eb-99a6-fb310e78e57b.png)
