### ISSUE TITLE
Callback script that sends measurements to a FHIR server

### ISSUE THREAD

**Issue by luckfamousa** [JsBergbau/MiTemperature2#82]
I am using the sensors to capture temperature and humidity in a hospital environment.
Because we are running a FHIR server (https://www.hl7.org/fhir/) the script encodes the measurements as FHIR Observations (https://www.hl7.org/fhir/observation.html) and sends them to the FHIR server. You might want to add it to the collection of callback scripts in case it is of interest for someone else:

https://gist.github.com/luckfamousa/2e56559238454ca5e1953641c2a5dbc5

**Comment by JsBergbau** [comment]
Hi @luckfamousa 
sorry for late reply. Thanks for your contribution. I've added your callback script.
