### ISSUE TITLE
Node Red Callback and Dashboard

### ISSUE THREAD

**Issue by Sukalo0290** [JsBergbau/MiTemperature2#87]
Apologies, i'm pretty new to all this. I'm struggling with MQTT so using the Callback flow.

I want to display the gauges and charts directly on the Node Red Dashboard so i have two questions about this. firstly the device is connecting and bringing in the advertisements using the atc, the packet seems to be split up firstly which is proving difficult to use the split or function to extract the individual measurements to send the temperature to one graph and humidity to another.

![image](https://user-images.githubusercontent.com/29959318/119256614-7028d480-bbb9-11eb-9e45-41dc36377952.png)

Also where is this data or how to i setup the http as i don't seem to get any data from this area.
![image](https://user-images.githubusercontent.com/29959318/119256673-c3028c00-bbb9-11eb-8848-759f51a6be01.png)

Thanks for any assistance.

**Comment by JsBergbau** [comment]
Your data is recognised as string and not as JSON. 

What is your commandline to send the data to node red? Whats inside your callback script? Did you edit the IP address to point to your Node-RED instance?

**Comment by Sukalo0290** [comment]
So i imported the Callback file which populates all the nodes for me, I then deploy and press the start button
![image](https://user-images.githubusercontent.com/29959318/119260499-f26dc480-bbca-11eb-920a-6217bc8c35e1.png)
then it produces the string as you say in the debug window.

I haven't done anything else.

**Comment by JsBergbau** [comment]
You have to edit sendToNodeRed.sh because there is the configuration with IP address to Node-RED.

**Comment by Sukalo0290** [comment]
Okay, what do i need to edit exactly?

**Comment by JsBergbau** [comment]
This is sendToNodeRed.sh

Please edit at the places in angle brackets `< >`

```
#!/bin/bash

#use e.g with that script: MySensor.sh 
#!/bin/bash
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
#$DIR/LYWSD03MMC.py --atc --watchdogtimer 5 --callback sendToNodeRed.sh

if [[ "$1" == *"rssi"* ]]
then
	curl -s -i -XPOST http://<YOURHOST>:<YOURPORT>/MiTemperature2Input -H "Content-Type: application/json" --data "{\"sensor\": \"$2\", \"temperature\" : $3 , \"humidity\" : $4 , \"voltage\" :$5, \"rssi\" : $6, \"timestamp\": $7 }"
else
	curl -s -i -XPOST http://<YOURHOST>:<YOURPORT>/MiTemperature2Input -H "Content-Type: application/json" --data "{\"sensor\": \"$2\", \"temperature\" : $3 , \"humidity\" : $4 , \"voltage\" :$5, \"timestamp\": $6 }"
fi
```

**Comment by Sukalo0290** [comment]
Thanks for the response, i have actually managed to get the MQTT working today so now i'm trying to connect the influxdb so i can show the results on grafana or something but there doesn't seem to be any input yet so still working on it. I'm sure i'll be back if can't sort it.
