### ISSUE TITLE
LYWSD02 support?

### ISSUE THREAD

**Issue by skibbipl** [JsBergbau/MiTemperature2#9]
I successfully connected two LYWSD03MMC sensors but I have also 02 sensor. Can this script support those?

**Comment by JsBergbau** [comment]
Sorry, I don't understand. Do you mean a second sensor or another sensor type? If it is another sensor type, than it isn't supported by this script.

**Comment by skibbipl** [comment]
Yes, I mean another sensor type. It has e-ink display and clock. But I guess I'll have to stick to this:
https://github.com/h4/lywsd02

**Comment by jaggil** [comment]
> Yes, I mean another sensor type. It has e-ink display and clock. But I guess I'll have to stick to this:
> https://github.com/h4/lywsd02

**Comment by JsBergbau** [comment]
@skibbipl 
Did you try? Does this script work with LYWSD02 ?

**Comment by BLahr** [comment]
Guten Tag,

vielen Dank für Ihre Nachricht.
Ich arbeite nicht mehr für die WKG Software GmbH.
 
Bitte beachten Sie, dass Ihre Email nicht weitergeleitet wird. 
 
Bitte wenden Sie sich je nach Fall an eine dieser beiden Adressen:
support@salesfrontapp.com
telephonesupport@wkg-software.de 


Mit freundlichen Grüßen  

-----------------------------------------------------------------------------------  

Bastian Lahr (lahr@wkg-software.de)  

   

W.K.G Software GmbH  

Hindenburgstr. 38, 30175 Hannover, Germany  

Geschäftsführer: Dipl.-Kfm. Jochen Wunder  

HRB 60250 Amtsgericht Hannover, USt.-ID: DE 813 392 760  

-----------------------------------------------------------------------------------
