### ISSUE TITLE
mqtt.conf ' not found

### ISSUE THREAD

**Issue by Sukalo0290** [JsBergbau/MiTemperature2#90]
I'm struggling to get the MQTT working and have got up to `mqtt.conf ' not found` using node red.

I have installed everything as per the instructions but what do i need to edit in the mqtt.conf if anything? Does this method need port forwarding or is the mqtt message local in the machine?

Does paho use mosquitto or are they seperate mqtt brokers? Is there additional setup i need to do for paho?

**Comment by JsBergbau** [comment]
Hi Sukalo0290 

Try to specify absolut path of mqtt.conf in Node-RED, then it should work.

**Comment by Sukalo0290** [comment]
I realised it is the path issue, found where to place the file and kicked in. Cheers.
