### ISSUE TITLE
Attaching a DS18B20 probe Data wire location

### ISSUE THREAD

**Issue by Sukalo0290** [JsBergbau/MiTemperature2#92]
I plan on adding one of these water proof probes to replace the sensor but i'm wondering where the data wire would be attached.

![image](https://user-images.githubusercontent.com/29959318/123111481-dc0a9100-d434-11eb-9b6b-37c671f1f2f0.png)

I plan on editing this file 
https://github.com/atc1441/ATC_MiThermometer/blob/master/ATC_Thermometer/sensor.c

Where would i attach the data wire? I have seen the diagram but where would the data cable go?

Red connects to 3-5V - already know
Blue/Black connects to ground - already know
Yellow/White is data - not sure

![image](https://user-images.githubusercontent.com/29959318/123111946-3a377400-d435-11eb-99b4-7539e05e3623.png)

**Comment by JsBergbau** [comment]
Hi Sukalo0290,
thanks for your interest. However I'm just developing a script to read transmitted data. So I can't help you to connect the DS18B20 to LYWSD03MMC Temperature sensor. I don't even know whether firmware can read the data or not. 
I see you have already asked it there https://github.com/pvvx/ATC_MiThermometer/issues/105 
So I'm closing here.

**Comment by Sukalo0290** [comment]
No problem, i didn't know if these questions would reach others who might be able to help. But thanks for all your work already, script all working great.
